name: "Continuous Integration"

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    check-dependencies:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.2
                  coverage: none

            - name: Install dependencies
              uses: ramsey/composer-install@v3
              with:
                  dependency-versions: ${{ matrix.dependencies }}

    php-cs-fixer:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.2
                  coverage: none

            - name: Install dependencies
              uses: ramsey/composer-install@v3
              with:
                  dependency-versions: ${{ matrix.dependencies }}

            - name: PHP-CS-Fixer
              run: php vendor/bin/php-cs-fixer fix --dry-run --diff --no-ansi

    phpstan:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.2
                  coverage: none

            - name: Install dependencies
              uses: ramsey/composer-install@v3
              with:
                  dependency-versions: ${{ matrix.dependencies }}

            - name: PHPStan
              run: php vendor/bin/phpstan analyse

    phpunit:
        strategy:
            matrix:
                operating-system: [ 'ubuntu-latest' ]
                php-version: [ '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3' ]

        runs-on: ${{ matrix.operating-system }}

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php_version }}
                  coverage: none

            - name: Install dependencies
              uses: ramsey/composer-install@v3
              with:
                  dependency-versions: ${{ matrix.dependencies }}

            - name: Test PHPUnit
              run: php vendor/bin/phpunit